load(paste(file_path, "/vital_logr.rda", sep = ""))
drug_vars <- c("Avastin", "BCNU", "CCNU", "CPT.11", "Dexamethasone", "Gliadel.Wafer",  
                           "Other_drug", "Tarceva", "Temozolomide", "VP.16")
radiation_vars <- c("EXTERNAL.BEAM", "Other_radiation")


evaluate_node <- function(bit_string, treatment_options, n_options, demog_ch_vars, vital.logr, response_var)
{
  columns <- setdiff(c(demog_ch_vars, treatment_options), dropped_columns)
  test_row <- data.frame(matrix(ncol = length(columns)))
  colnames(test_row) <- columns
  
  #Values for demo and case history variables are obtained from input form

  test_row[1, "age_at_initial_pathologic_diagnosis"] <- 59
  test_row[1, "ethnicity"] <- 'NOT HISPANIC OR LATINO'
  test_row[1, "gender"] <- 'FEMALE'
  test_row[1, "race"] <- 'WHITE'
  test_row[1, "histological_type"] <- 'Untreated primary (de novo) GBM'
  test_row[1, "history_of_neoadjuvant_treatment"] <- 'No'
  test_row[1, "initial_pathologic_diagnosis_method"] <- 'Tumor resection'
  test_row[1, "karnofsky_performance_score"] <- 80
  test_row[1, "person_neoplasm_cancer_status"] <- 'WITH TUMOR'
  test_row[1, "prior_glioma"] <- 'NO'

  for (j in 1:n_options)
   {
     if (bit_string[j])
     {
       test_row[1, treatment_options[j]] = 'TRUE'
     }
     else
     {
       test_row[1, treatment_options[j]] = 'FALSE'
     }
   }
  for (column in columns)
  {
    if (column != response_var & is.factor(dense_matrix[, column]))
    { 
      test_row[, column] <- factor(test_row[, column], levels = levels(dense_matrix[, column]))
    }
  }
  cond_prob = predict(vital.logr, test_row, type = "response")
}


custom_hill_climbing_for_optimal <- function(dense_matrix)
{
  treatment_options <- sort(append(drug_vars, radiation_vars))
  n_options <- length(treatment_options)
  bit_string <- rep(FALSE, length(treatment_options))

  #pick an option at random, to start with. A node is an assignment of values to the evidence variables.
  current <- sample(treatment_options, 1)
  bit_string[which(treatment_options == current)] <- TRUE
  
  #Fix some values for the demographic and case history variables, for now
  demog_ch_vars <- c("age_at_initial_pathologic_diagnosis", "ethnicity", "gender", "race", "histological_type", "history_of_neoadjuvant_treatment", 
                     "initial_pathologic_diagnosis_method", "karnofsky_performance_score", "person_neoplasm_cancer_status", "prior_glioma")
  current_val <- evaluate_node(bit_string, treatment_options, n_options, demog_ch_vars, vital.logr, "lived_past_one_year")
 
  while (TRUE)
  {
    cat(paste("current evidence = ", convert_bit_string_to_evidence(bit_string, treatment_options, n_options), ", current_val = ", current_val, "\n\n", sep = ""))
    #Generate all neighbors of current by a successor function. The neighbors are generated by toggling one 
    #bit in bit_string at a time
    max_score_from_neighbor <- 0
    for (i in 1:n_options)
    {
        #Generate a neighbor by toggling the i-th bit of bit_string
        neighbor_bit_string <- bit_string
        neighbor_bit_string[i] <- !bit_string[i]
        #All 0s can be generated as a neighbor but it is not a valid evidence, so skip it
        if (sum(neighbor_bit_string) > 0)
        {
          #Generate the evidence corresponding to the neighbor
          this_neighbor_val <- evaluate_node(neighbor_bit_string, treatment_options, n_options, demog_ch_vars, vital.logr, "lived_past_one_year")
          #cat(paste("this_neighbor_val = ", this_neighbor_val, "\n", sep = ""))
          if (this_neighbor_val > max_score_from_neighbor)
          {
            max_score_from_neighbor <- this_neighbor_val
            highest_scoring_neighbor <- neighbor_bit_string
          }
        }
    }
    #Now, all neighbors are processed for current node
    if (max_score_from_neighbor <= current_val)
    {
      cat(paste("Reached maxima at ", current_val, "\n", sep = "")) 
      return(bit_string)
    }
    #Setting current to highest scoring neighbor for the next iteration. bit_string represents the current node
    bit_string <- highest_scoring_neighbor
    current_val <- max_score_from_neighbor
    #cat(paste("score rising to = ", max_score_from_neighbor, ", new current is ", convert_bit_string_to_evidence(bit_string, treatment_options, n_options), "\n\n", sep = ""))
    if (max_score_from_neighbor == 1)
    {
      return(highest_scoring_neighbor)
    }
  }
}

# Define server logic required to do the hill climbing for a given patient
shinyServer(function(input, output) {
  
})
