file_path <- "/Users/blahiri/healthcare/data/tcga/Raw_Data/v3"
load(paste(file_path, "/vital_logr.rda", sep = ""))
drug_vars <- c("Avastin", "BCNU", "CCNU", "CPT.11", "Dexamethasone", "Gliadel.Wafer",  
                           "Other_drug", "Tarceva", "Temozolomide", "VP.16")
radiation_vars <- c("EXTERNAL.BEAM", "Other_radiation")

inputs_for_demog_ch <<- list()

#The input is a bit vector that specifies a chromosome, which essentially 
#tells which of the treatment options will be used. The output is the negative of the 
#linear combination generated by logistic regression. The negative is taken because 
#rbga.bin only minimizes the objective function.

evalFunc <- function(bit_string)
{
  
  file_path <- "/Users/blahiri/healthcare/data/tcga/Raw_Data/v3"
  load(paste(file_path, "/vital_logr.rda", sep = ""))

  obj_func <- as.numeric(vital.logr$coefficients[1:16]) %*% as.numeric(inputs_for_demog_ch)

  obj_func <- obj_func + as.numeric(vital.logr$coefficients[17:28]) %*% bit_string
  n_bits <- length(bit_string)
  if ((sum(bit_string) > 3) || (sum(bit_string[(n_bits-1): n_bits]) == 2))
  {
    return(0)
  }
  else
  {
    return(-obj_func)
  }
}

genetic_algorithm_for_optimal <- function(input_data)
{
  library(genalg)
  treatment_options <- sort(append(drug_vars, radiation_vars))
  n_options <- length(treatment_options)

  inputs_for_demog_ch[["intercept_coeff"]] <<- 1
  inputs_for_demog_ch[["age_at_initial_pathologic_diagnosis"]] <<- input_data[["age_at_initial_pathologic_diagnosis"]]
  inputs_for_demog_ch[["ethnicityHISPANIC OR LATINO"]] <<- as.numeric(input_data[["ethnicity"]] == 'HISPANIC OR LATINO')
  inputs_for_demog_ch[["genderMALE"]] <<- as.numeric(input_data[["gender"]] == 'MALE')
  inputs_for_demog_ch[["histological_typeTreated primary GBM"]] <<- as.numeric(input_data[["histological_type"]] == 'Treated primary GBM')
  inputs_for_demog_ch[["histological_typeGlioblastoma Multiforme (GBM)"]] <<- as.numeric(input_data[["histological_type"]] == 'Glioblastoma Multiforme (GBM)')
  inputs_for_demog_ch[["history_of_neoadjuvant_treatmentNo"]] <<- as.numeric(input_data[["history_of_neoadjuvant_treatment"]] == 'No')
  inputs_for_demog_ch[["initial_pathologic_diagnosis_methodExcisional Biopsy"]] <<- as.numeric(input_data[["initial_pathologic_diagnosis_method"]] == 'Excisional Biopsy')
  inputs_for_demog_ch[["initial_pathologic_diagnosis_methodIncisional Biopsy"]] <<- as.numeric(input_data[["initial_pathologic_diagnosis_method"]] == 'Incisional Biopsy')
  inputs_for_demog_ch[["initial_pathologic_diagnosis_methodOther method, specify"]] <<- as.numeric(input_data[["initial_pathologic_diagnosis_method"]] == 'Other method, specify')
  inputs_for_demog_ch[["initial_pathologic_diagnosis_methodFine needle aspiration biopsy"]] <<- as.numeric(input_data[["initial_pathologic_diagnosis_method"]] == 'Fine needle aspiration biopsy')
  inputs_for_demog_ch[["karnofsky_performance_score"]] <<- input_data[["karnofsky_performance_score"]]
  inputs_for_demog_ch[["person_neoplasm_cancer_statusTUMOR FREE"]] <<- as.numeric(input_data[["person_neoplasm_cancer_status"]] == 'TUMOR FREE')
  inputs_for_demog_ch[["prior_gliomaYES"]] <<- as.numeric(input_data[["prior_glioma"]] == 'YES')
  inputs_for_demog_ch[["raceBLACK OR AFRICAN AMERICAN"]] <<- as.numeric(input_data[["race"]] == 'BLACK OR AFRICAN AMERICAN')
  inputs_for_demog_ch[["raceASIAN"]] <<- as.numeric(input_data[["race"]] == 'ASIAN')
  
  
  GAmodel <- rbga.bin(size = n_options, popSize = 200, iters = 6, 
                      mutationChance = 1/(n_options + 1), elitism = T, evalFunc = evalFunc, verbose = TRUE)
  df <- process_output_of_genetic(GAmodel, treatment_options)
}

#Rank the chromosomes of the final population by evaluation. Since the GA 
#minimizes the objective function, the lower the evaluation, the higher they should 
#be ranked. Survival probability = sigmoid(-evaluation)

process_output_of_genetic <- function(GAmodel, treatment_options)
{
  library(boot)
  df <- as.data.frame(GAmodel$population)
  df$evaluation <- GAmodel$evaluations
  df$surv_prob <- inv.logit(-df$evaluation)
  df <- df[order(-df[, "surv_prob"]),]
  df <- df[!duplicated(df), ]
  df$combination <- apply(df, 1, function(row) convert_bit_string_to_text(row[paste("V", 1:12, sep = "")], treatment_options)) 
  df <- df[,!(names(df) %in% c("evaluation", paste("V", 1:12, sep = "")))]
  row.names(df) <- NULL
  df <- df[c(2,1)]
  colnames(df) <- c("Combination", "1-year survival probability")
  df
}

convert_bit_string_to_text <- function(bit_string, treatment_options)
{
  paste(treatment_options[which(bit_string == 1)], collapse = ", ")
}



# Define server logic required to do the hill climbing for a given patient
shinyServer(function(input, output) {

  datasetInput <- reactive({

    age_at_initial_pathologic_diagnosis <- input$age_at_initial_pathologic_diagnosis
    ethnicity <- input$ethnicity
    gender <- input$gender
    race <- input$race
    histological_type <- input$histological_type
    history_of_neoadjuvant_treatment <- input$history_of_neoadjuvant_treatment
    initial_pathologic_diagnosis_method <- input$initial_pathologic_diagnosis_method
    karnofsky_performance_score <- input$karnofsky_performance_score
    person_neoplasm_cancer_status <- input$person_neoplasm_cancer_status
    prior_glioma <- input$prior_glioma

    list("age_at_initial_pathologic_diagnosis" = age_at_initial_pathologic_diagnosis, 
         "ethnicity" = ethnicity, "gender" = gender, "race" = race, "histological_type" = histological_type,
         "history_of_neoadjuvant_treatment" = history_of_neoadjuvant_treatment, "initial_pathologic_diagnosis_method" = initial_pathologic_diagnosis_method,
         "karnofsky_performance_score" = karnofsky_performance_score, "person_neoplasm_cancer_status" = person_neoplasm_cancer_status,
         "prior_glioma" = prior_glioma)
  })

  output$ranked_results <- renderTable({
    
    input_data <- datasetInput()
    genetic_algorithm_for_optimal(input_data)
  })
})










